#!$(which zsh)
alias ls="exa -a --color=always --icons --group-directories-first"
alias ll="exa -la --color=always --icons --group-directories-first"
alias tree="exa -a --color=always --icons --group-directories-first -T"
alias lz="lazygit"
alias v="nvim"
alias gt="gotop"
